name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: deploy gh-pages
   
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    
    - name: Commit files
      run: |
        npm run deploy
